### ISSUE TITLE
DBIx::Skinny#set_dbh is not worked.

### ISSUE THREAD

**Issue by walf443** [nekokak/p5-dbix-skinny#1]
DBIx::Skinny#set_dbhは@functionsに列挙されてなくて、exportされてないのでユーザーの作ったクラスで呼べないもよう。

connect_infoとかを期待して動作してる挙動があって、その辺でどうもうまく動いていないっぽい。
そのあたりを考慮すると、うまく作りづらいのでAPIをなくしてもよいのかも。

**Comment by nekokak** [comment]
対応した。サンクス。issuesの使い方わかりません。
